name: Update readme with blog posts
on:
  workflow_dispatch:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@a1daea7354236efd6b95d75e77b45f8a2dd88199
        with:
          feed-url: https://duendesoftware.com/rss.xml
          readme-section: feed
          max: 8
          template: "* [{{ title }}]({{ link }}) \n"